# Generated by Django 5.0.2 on 2024-05-22 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_remove_chef_name_remove_recipe_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='chef.chef'),
        ),
    ]
