# Generated by Django 5.0.2 on 2024-05-22 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0003_alter_recipe_chef'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
